### ISSUE TITLE
[FEAT]: Enhance User Profiles

### ISSUE THREAD

**Issue by Anushka-Pote** [Metamorphosis21/P4_ChatApp#8]
### **Description**
Add customization options for user profiles, allowing users to set a status message and select a theme for their chat interface.

### **Acceptance Criteria**
- Users can set a visible status message.
- Users can choose from a selection of themes for their chat interface.

### **Tasks**
1. Implement an input field for users to enter a status message and save it in the database.
2. Create a theme selection option, allowing users to pick from at least three themes.
3. Update the user profile UI to include these new features.

### **Additional Details**
- Ensure the status message has a character limit.
- Consider using local storage for theme selection before saving it to the database.

**Comment by Metamorphosis21** [comment]
After completion of the feature do share a screenshot of it

**Comment by Anushka-Pote** [comment]
I am even a contributor for gssoc-ext, so can you add those labels also to it?
